# Generated by Django 2.0 on 2018-02-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('patronymic', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_code', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('course', models.CharField(blank=True, max_length=3)),
                ('sub_number', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.TextField(blank=True)),
                ('september', models.TextField(blank=True)),
                ('october', models.TextField(blank=True)),
                ('december', models.TextField(blank=True)),
                ('january', models.TextField(blank=True)),
                ('february', models.TextField(blank=True)),
                ('march', models.TextField(blank=True)),
                ('april', models.TextField(blank=True)),
                ('may', models.TextField(blank=True)),
                ('june', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('group_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Replacements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('week', models.IntegerField(blank=True)),
                ('number_learn', models.IntegerField(blank=True)),
                ('custom_learn', models.CharField(blank=True, max_length=30)),
                ('custom_teacher', models.CharField(blank=True, max_length=30)),
                ('classroom', models.CharField(blank=True, max_length=5)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True)),
                ('day', models.CharField(blank=True, max_length=15)),
                ('learnings', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('patronymic', models.CharField(blank=True, max_length=15)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_code', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('pm_module', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('patronymic', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users_login',
            fields=[
                ('login', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('user_type', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='login',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Users_login'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='supervised_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups'),
        ),
        migrations.AddField(
            model_name='students',
            name='login',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Users_login'),
        ),
        migrations.AddField(
            model_name='replacements',
            name='learn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Subjects'),
        ),
        migrations.AddField(
            model_name='replacements',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Teachers'),
        ),
        migrations.AddField(
            model_name='admins',
            name='login',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Users_login'),
        ),
    ]
