# Generated by Django 2.0 on 2018-02-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ivents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('info', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Teachers')),
            ],
        ),
        migrations.AddField(
            model_name='journals',
            name='november',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='course',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='sub_number',
            field=models.IntegerField(blank=True),
        ),
    ]
