# Generated by Django 2.0 on 2018-02-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej', '0002_auto_20180226_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Users_login'),
        ),
        migrations.AlterField(
            model_name='ivents',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Teachers'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='group_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups'),
        ),
        migrations.AlterField(
            model_name='replacements',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups'),
        ),
        migrations.AlterField(
            model_name='replacements',
            name='learn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Subjects'),
        ),
        migrations.AlterField(
            model_name='replacements',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Teachers'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups'),
        ),
        migrations.AlterField(
            model_name='students',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Users_login'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Users_login'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='supervised_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.Groups'),
        ),
    ]
