from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'logout$', views.logout, name='logout'),
    url(r'teacher/log$', views.teacher_log, name='teacher_log'),
    url(r'teacher/module$', views.teacher_module, name='teacher_module'),
    url(r'teacher/logbook$', views.teacher_logbook, name='teacher_logbook'),
    url(r'teacher/schedule_teacher$', views.teacher_schedule_teacher, name='teacher_schedule_teacher'),
    url(r'teacher/table$', views.teacher_table, name='teacher_table'),
    url(r'teacher/load$', views.teacher_load, name='teacher_load'),
    url(r'teacher/group$', views.teacher_group, name='teacher_group'),
    url(r'teacher/curator$', views.teacher_curator, name='teacher_curator'),
    url(r'teacher/info$', views.teacher_info, name='teacher_info'),
    url(r'student/schedule$', views.student_schedule, name='student_schedule'),
    url(r'student/info$', views.student_info, name='student_info'),
    url(r'student/marks$', views.student_marks, name='student_marks'),
    url(r'admin/info$', views.admin_info, name='admin_info'),
    url(r'admin/schedule_edit$', views.admin_schedule_edit, name='admin_schedule_edit'),
    url(r'admin/replacement_edit$', views.admin_replacement_edit, name='admin_replacement_edit'),
    url(r'admin/log_edit$', views.admin_log_edit, name='admin_log_edit'),
    url(r'admin/module_edit$', views.admin_module_edit, name='admin_module_edit'),
    url(r'admin/load_edit$', views.admin_load_edit, name='admin_load_edit'),
    url(r'admin/group_edit$', views.admin_group_edit, name='admin_group_edit'),
    url(r'admin/statistics$', views.admin_statistics, name='admin_statistics'),
    url(r'admin/students_edit$', views.admin_students_edit, name='admin_students_edit'),
    url(r'admin/teacher_edit$', views.admin_teacher_edit, name='admin_teacher_edit'),
    url(r'edit/journal$', views.edit_journal, name='edit_journal'),
]
